---
abstract: "Parse Toikatsu Dojo's schedule.pdf and print jsonl for RecordStream."
author:
  - 'Tomohiro Hosaka'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '7.1101'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-RecordStream-TKDJ
requires:
  Algorithm::Combinatorics: '0'
  Algorithm::Line::Bresenham: '0'
  App::Cmd: '0'
  Color::Similarity: '0'
  Convert::Color: '0'
  IO::All: '0'
  Image::Magick: '0'
  JSON::MaybeXS: '0'
  Lingua::JA::Regular::Unicode: '0'
  List::UtilsBy: '0'
  Modern::Perl: '0'
  Text::Trim: '0'
  XML::Twig: '0'
  rlib: '0'
version: '0.02'
x_generated_by_perl: v5.26.2
x_serialization_backend: 'YAML::Tiny version 1.73'
